# name: Deploy to GKE Autopilot

# on:
#   push:
#     branches:
#       - main
#       - Dev

# env:
#   PROJECT_ID: devops-project-419807
#   CLUSTER_NAME: autopilot-cluster-1
#   ZONE: asia-east1

# jobs:
#   deploy:
#     name: Deploy to GKE Autopilot
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup JDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'corretto'
#           java-version: 17

#       - name: Build the application
#         run: |
#           mvn clean
#           mvn -B package --file pom.xml
      
#       - name: Authenticate
#         uses: google-github-actions/auth@v2
#         with: 
#           credentials_json: ${{ secrets.GCP_SA_KEY }}
          
#       - name: Configure gcloud
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           install_components: 'gke-gcloud-auth-plugin'

#       # - name: Login to Docker Hub
#       #   uses: docker/login-action@v1
#       #   with:
#       #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
#       #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Build and Push the docker image
#         env:
#           GOOGLE_PROJECT: ${{ env.PROJECT_ID }}
#         run: |
#           gcloud auth configure-docker asia-east1-docker.pkg.dev
#           docker build -t asia-east1-docker.pkg.dev/devops-project-419807/backend/gke_springapp:1.0 .
#           docker push asia-east1-docker.pkg.dev/$GOOGLE_PROJECT/backend/gke_springapp:1.0

#       # - name: Build Image
#       #   uses: docker/build-push-action@v2
#       #   with:
#       #     context: .
#       #     push: true
#       #     tags: gcr.io/${{ env.PROJECT_ID }}/gke_springapp:1.0

#       - name: Set cluster context
#         run: |
#           gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project ${{ env.PROJECT_ID }}

#       - name: Apply Kubernetes manifests
#         run: |
#           kubectl apply -f resources.yaml
   



          